# Docker Compose file -- defines how to run the project's containers

services:
  # The Django web application
  web:
    # Build the image using the Dockerfile in the current directory (./Dockerfile)
    build: .

    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}

    # Map port 8000 on your machine to port 8000 in the container
    # Access the app at http://localhost:8000
    ports:
      - "8000:8000"

    # Mount the current directory into /app in the container
    # This means code changes on your machine are reflected instantly (live reload)
    volumes:
      - .:/app  # "." = your project folder, "/app" = where it goes inside the container
      - django_static:/app/staticfiles # Map static files for production-readiness
      - django_media:/app/media        # Map media files for uploads

# Named volumes (folders managed by Docker that live outside the containers)
# They keep data even if you delete and recreate the containers
volumes:
  django_media:
  django_static: