# Generated by Django 6.0.5 on 2026-06-11 03:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='default_profile', max_length=255, verbose_name='image'),
        ),
    ]
