# Generated by Django 6.0.5 on 2026-05-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_platform_p_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovisualcontent',
            name='backdrop_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Backdrop URL'),
        ),
        migrations.AddField(
            model_name='audiovisualcontent',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Poster URL'),
        ),
    ]
