# Generated by Django 5.0.2 on 2026-05-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_onboarding_completed_alter_agerating_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPlatform',
        ),
    ]
