# Generated by Django 6.0.5 on 2026-06-11 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_profile_picture'),
        ('app', '0003_create_watchlist_content_m2m'),
    ]

    operations = [
    ]
