# Generated by Django 5.0.2 on 2026-05-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='banner',
        ),
    ]
